FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_BACKEND_HTTP_URL
ARG NEXT_PUBLIC_BACKEND_WS_URL

ENV NEXT_PUBLIC_BACKEND_HTTP_URL=$NEXT_PUBLIC_BACKEND_HTTP_URL
ENV NEXT_PUBLIC_BACKEND_WS_URL=$NEXT_PUBLIC_BACKEND_WS_URL

COPY package*.json ./
COPY turbo.json ./
COPY tsconfig*.json ./
COPY apps ./apps
COPY packages ./packages

RUN npm install
RUN npx turbo run build --filter=frontend...

CMD ["npm", "run", "start", "--workspace=apps/frontend", "--", "--hostname", "0.0.0.0", "--port", "3000"]