FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./
COPY tsconfig*.json ./
COPY apps ./apps
COPY packages ./packages

RUN npm install
RUN npx prisma generate --schema=apps/backend/prisma/schema.prisma
RUN npx turbo run build --filter=backend...

CMD ["sh", "-c", "npx prisma migrate deploy --config=apps/backend/prisma.config.ts --schema=apps/backend/prisma/schema.prisma && npm run start:prod --workspace=apps/frontend"]